version: "3.7"
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        depends_on:
            - alpha
            - zero
            - redis
        ports:
            - "8080:8080"
        env_file: ./server/.env
        environment:
            PORT: 8080
            REDIS_HOST: redis:6379
    finder:
        build:
            context: ./finder
            dockerfile: Dockerfile
        depends_on:
            - redis
            - server
        ports:
            - "8070:8070"
            - "50051:50051"
        # env_file: ./finder/.env
        environment:
            PORT: 8070
            TCP_PORT: 50051
            REDIS_HOST: redis:6379
    # translator:
    #    build:
    #        context: ./translator
    #        dockerfile: Dockerfile
    #    depends_on:
    #        - redis
    #    ports:
    #        - "8090:8090"
    #    environment:
    #        GOSPIGA_REDIS_HOST: redis:6379
    #    volumes:
    #        - ./translator/gcloud-key.json:/gcloud-key.json
    redis:
        image: redislabs/redisearch:latest
        ports:
            - "6379:6379"
        volumes:
            - type: volume
              source: redis
              target: /data
              volume:
                  nocopy: true
        command: ["redis-server", "--appendonly", "yes", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
    zero:
        image: dgraph/dgraph:v20.03.0
        volumes:
            - type: volume
              source: dgraph
              target: /dgraph
              volume:
                  nocopy: true
        ports:
            - 5080:5080
            - 6080:6080
            - 8060:8080
            - 9060:9080
        restart: on-failure
        command: dgraph zero --my=zero:5080
    alpha:
        image: dgraph/dgraph:v20.03.0
        volumes:
            - type: volume
              source: dgraph
              target: /dgraph
              volume:
                nocopy: true
        ports:
            - 8090:8080
            - 9080:9080
        restart: on-failure
        command: dgraph alpha --my=alpha:7080 --lru_mb=2048 --zero=zero:5080
    ratel:
        image: dgraph/dgraph:v20.03.0
        volumes:
            - type: volume
              source: dgraph
              target: /dgraph
              volume:
                  nocopy: true
        ports:
            - 8000:8000
        command: dgraph-ratel

volumes:
    dgraph:
    redis:
