// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gospiga

type NewRecipe struct {
	Title string `json:"title,omitempty"`
}

type Recipe struct {
	UID       string `json:"uid,omitempty"`
	Title     string `json:"title,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	URL       string `json:"url,omitempty"`
}
