// Code generated by protoc-gen-go. DO NOT EDIT.
// source: finder.proto

package finder

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRecipesRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRecipesRequest) Reset()         { *m = SearchRecipesRequest{} }
func (m *SearchRecipesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRecipesRequest) ProtoMessage()    {}
func (*SearchRecipesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02dfec63316bfb34, []int{0}
}

func (m *SearchRecipesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRecipesRequest.Unmarshal(m, b)
}
func (m *SearchRecipesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRecipesRequest.Marshal(b, m, deterministic)
}
func (m *SearchRecipesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRecipesRequest.Merge(m, src)
}
func (m *SearchRecipesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRecipesRequest.Size(m)
}
func (m *SearchRecipesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRecipesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRecipesRequest proto.InternalMessageInfo

func (m *SearchRecipesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchRecipesResponse struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRecipesResponse) Reset()         { *m = SearchRecipesResponse{} }
func (m *SearchRecipesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchRecipesResponse) ProtoMessage()    {}
func (*SearchRecipesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02dfec63316bfb34, []int{1}
}

func (m *SearchRecipesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRecipesResponse.Unmarshal(m, b)
}
func (m *SearchRecipesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRecipesResponse.Marshal(b, m, deterministic)
}
func (m *SearchRecipesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRecipesResponse.Merge(m, src)
}
func (m *SearchRecipesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchRecipesResponse.Size(m)
}
func (m *SearchRecipesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRecipesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRecipesResponse proto.InternalMessageInfo

func (m *SearchRecipesResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchRecipesRequest)(nil), "SearchRecipesRequest")
	proto.RegisterType((*SearchRecipesResponse)(nil), "SearchRecipesResponse")
}

func init() { proto.RegisterFile("finder.proto", fileDescriptor_02dfec63316bfb34) }

var fileDescriptor_02dfec63316bfb34 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcb, 0xcc, 0x4b,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe1, 0x12, 0x09, 0x4e, 0x4d, 0x2c,
	0x4a, 0xce, 0x08, 0x4a, 0x4d, 0xce, 0x2c, 0x48, 0x2d, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x12, 0xe1, 0x62, 0x2d, 0x2c, 0x4d, 0x2d, 0xaa, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0x70, 0x94, 0x34, 0xb9, 0x44, 0xd1, 0x54, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x09,
	0x70, 0x31, 0x67, 0xa6, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x06, 0x81, 0x98, 0x46, 0x5e,
	0x5c, 0x6c, 0x6e, 0x60, 0x8b, 0x84, 0x1c, 0xb8, 0x78, 0x51, 0x34, 0x09, 0x89, 0xea, 0x61, 0xb3,
	0x52, 0x4a, 0x4c, 0x0f, 0xab, 0xd9, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xb7, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x0e, 0x8a, 0x70, 0x1d, 0xbb, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FinderClient is the client API for Finder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FinderClient interface {
	SearchRecipes(ctx context.Context, in *SearchRecipesRequest, opts ...grpc.CallOption) (*SearchRecipesResponse, error)
}

type finderClient struct {
	cc *grpc.ClientConn
}

func NewFinderClient(cc *grpc.ClientConn) FinderClient {
	return &finderClient{cc}
}

func (c *finderClient) SearchRecipes(ctx context.Context, in *SearchRecipesRequest, opts ...grpc.CallOption) (*SearchRecipesResponse, error) {
	out := new(SearchRecipesResponse)
	err := c.cc.Invoke(ctx, "/Finder/SearchRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinderServer is the server API for Finder service.
type FinderServer interface {
	SearchRecipes(context.Context, *SearchRecipesRequest) (*SearchRecipesResponse, error)
}

// UnimplementedFinderServer can be embedded to have forward compatible implementations.
type UnimplementedFinderServer struct {
}

func (*UnimplementedFinderServer) SearchRecipes(ctx context.Context, req *SearchRecipesRequest) (*SearchRecipesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchRecipes not implemented")
}

func RegisterFinderServer(s *grpc.Server, srv FinderServer) {
	s.RegisterService(&_Finder_serviceDesc, srv)
}

func _Finder_SearchRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRecipesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinderServer).SearchRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Finder/SearchRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinderServer).SearchRecipes(ctx, req.(*SearchRecipesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Finder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Finder",
	HandlerType: (*FinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchRecipes",
			Handler:    _Finder_SearchRecipes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finder.proto",
}
