// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.8
// source: finder.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Finder_AllRecipeTags_FullMethodName = "/Finder/AllRecipeTags"
)

// FinderClient is the client API for Finder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinderClient interface {
	AllRecipeTags(ctx context.Context, in *AllRecipeTagsRequest, opts ...grpc.CallOption) (*AllRecipeTagsResponse, error)
}

type finderClient struct {
	cc grpc.ClientConnInterface
}

func NewFinderClient(cc grpc.ClientConnInterface) FinderClient {
	return &finderClient{cc}
}

func (c *finderClient) AllRecipeTags(ctx context.Context, in *AllRecipeTagsRequest, opts ...grpc.CallOption) (*AllRecipeTagsResponse, error) {
	out := new(AllRecipeTagsResponse)
	err := c.cc.Invoke(ctx, Finder_AllRecipeTags_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinderServer is the server API for Finder service.
// All implementations must embed UnimplementedFinderServer
// for forward compatibility
type FinderServer interface {
	AllRecipeTags(context.Context, *AllRecipeTagsRequest) (*AllRecipeTagsResponse, error)
	mustEmbedUnimplementedFinderServer()
}

// UnimplementedFinderServer must be embedded to have forward compatible implementations.
type UnimplementedFinderServer struct {
}

func (UnimplementedFinderServer) AllRecipeTags(context.Context, *AllRecipeTagsRequest) (*AllRecipeTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllRecipeTags not implemented")
}
func (UnimplementedFinderServer) mustEmbedUnimplementedFinderServer() {}

// UnsafeFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinderServer will
// result in compilation errors.
type UnsafeFinderServer interface {
	mustEmbedUnimplementedFinderServer()
}

func RegisterFinderServer(s grpc.ServiceRegistrar, srv FinderServer) {
	s.RegisterService(&Finder_ServiceDesc, srv)
}

func _Finder_AllRecipeTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllRecipeTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinderServer).AllRecipeTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Finder_AllRecipeTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinderServer).AllRecipeTags(ctx, req.(*AllRecipeTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Finder_ServiceDesc is the grpc.ServiceDesc for Finder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Finder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Finder",
	HandlerType: (*FinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllRecipeTags",
			Handler:    _Finder_AllRecipeTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finder.proto",
}
