// Code generated by protoc-gen-go. DO NOT EDIT.
// source: finder.proto

package finder

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AllRecipeTagsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllRecipeTagsRequest) Reset()         { *m = AllRecipeTagsRequest{} }
func (m *AllRecipeTagsRequest) String() string { return proto.CompactTextString(m) }
func (*AllRecipeTagsRequest) ProtoMessage()    {}
func (*AllRecipeTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02dfec63316bfb34, []int{0}
}

func (m *AllRecipeTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRecipeTagsRequest.Unmarshal(m, b)
}
func (m *AllRecipeTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRecipeTagsRequest.Marshal(b, m, deterministic)
}
func (m *AllRecipeTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRecipeTagsRequest.Merge(m, src)
}
func (m *AllRecipeTagsRequest) XXX_Size() int {
	return xxx_messageInfo_AllRecipeTagsRequest.Size(m)
}
func (m *AllRecipeTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRecipeTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllRecipeTagsRequest proto.InternalMessageInfo

type AllRecipeTagsResponse struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllRecipeTagsResponse) Reset()         { *m = AllRecipeTagsResponse{} }
func (m *AllRecipeTagsResponse) String() string { return proto.CompactTextString(m) }
func (*AllRecipeTagsResponse) ProtoMessage()    {}
func (*AllRecipeTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02dfec63316bfb34, []int{1}
}

func (m *AllRecipeTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRecipeTagsResponse.Unmarshal(m, b)
}
func (m *AllRecipeTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRecipeTagsResponse.Marshal(b, m, deterministic)
}
func (m *AllRecipeTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRecipeTagsResponse.Merge(m, src)
}
func (m *AllRecipeTagsResponse) XXX_Size() int {
	return xxx_messageInfo_AllRecipeTagsResponse.Size(m)
}
func (m *AllRecipeTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRecipeTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllRecipeTagsResponse proto.InternalMessageInfo

func (m *AllRecipeTagsResponse) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*AllRecipeTagsRequest)(nil), "AllRecipeTagsRequest")
	proto.RegisterType((*AllRecipeTagsResponse)(nil), "AllRecipeTagsResponse")
}

func init() { proto.RegisterFile("finder.proto", fileDescriptor_02dfec63316bfb34) }

var fileDescriptor_02dfec63316bfb34 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcb, 0xcc, 0x4b,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x12, 0xe3, 0x12, 0x71, 0xcc, 0xc9, 0x09,
	0x4a, 0x4d, 0xce, 0x2c, 0x48, 0x0d, 0x49, 0x4c, 0x2f, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x51, 0xd2, 0xe6, 0x12, 0x45, 0x13, 0x2f, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe2, 0x62,
	0x29, 0x49, 0x4c, 0x2f, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x02, 0xb3, 0x8d, 0xbc, 0xb8,
	0xd8, 0xdc, 0xc0, 0x86, 0x0a, 0x39, 0x70, 0xf1, 0xa2, 0x68, 0x13, 0x12, 0xd5, 0xc3, 0x66, 0xbc,
	0x94, 0x98, 0x1e, 0x56, 0xd3, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xee, 0x32, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0x84, 0xfc, 0x04, 0xa7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FinderClient is the client API for Finder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FinderClient interface {
	AllRecipeTags(ctx context.Context, in *AllRecipeTagsRequest, opts ...grpc.CallOption) (*AllRecipeTagsResponse, error)
}

type finderClient struct {
	cc *grpc.ClientConn
}

func NewFinderClient(cc *grpc.ClientConn) FinderClient {
	return &finderClient{cc}
}

func (c *finderClient) AllRecipeTags(ctx context.Context, in *AllRecipeTagsRequest, opts ...grpc.CallOption) (*AllRecipeTagsResponse, error) {
	out := new(AllRecipeTagsResponse)
	err := c.cc.Invoke(ctx, "/Finder/AllRecipeTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinderServer is the server API for Finder service.
type FinderServer interface {
	AllRecipeTags(context.Context, *AllRecipeTagsRequest) (*AllRecipeTagsResponse, error)
}

// UnimplementedFinderServer can be embedded to have forward compatible implementations.
type UnimplementedFinderServer struct {
}

func (*UnimplementedFinderServer) AllRecipeTags(ctx context.Context, req *AllRecipeTagsRequest) (*AllRecipeTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllRecipeTags not implemented")
}

func RegisterFinderServer(s *grpc.Server, srv FinderServer) {
	s.RegisterService(&_Finder_serviceDesc, srv)
}

func _Finder_AllRecipeTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllRecipeTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinderServer).AllRecipeTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Finder/AllRecipeTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinderServer).AllRecipeTags(ctx, req.(*AllRecipeTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Finder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Finder",
	HandlerType: (*FinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllRecipeTags",
			Handler:    _Finder_AllRecipeTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finder.proto",
}
