// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Food struct {
	Term string `json:"term"`
	Stem string `json:"stem"`
}

type Ingredient struct {
	Name          string    `json:"name"`
	Quantity      *string   `json:"quantity"`
	UnitOfMeasure *string   `json:"unitOfMeasure"`
	Food          *Food     `json:"food"`
	Recipes       []*Recipe `json:"recipes"`
}

type Recipe struct {
	Xid         string        `json:"xid"`
	Title       string        `json:"title"`
	Subtitle    string        `json:"subtitle"`
	MainImage   string        `json:"mainImage"`
	Likes       int           `json:"likes"`
	Difficulty  string        `json:"difficulty"`
	Cost        string        `json:"cost"`
	PrepTime    int           `json:"prepTime"`
	CookTime    *int          `json:"cookTime"`
	Servings    int           `json:"servings"`
	ExtraNotes  *string       `json:"extraNotes"`
	Description string        `json:"description"`
	Ingredients []*Ingredient `json:"ingredients"`
	Steps       []*Step       `json:"steps"`
	Conclusion  *string       `json:"conclusion"`
	Tags        []*Tag        `json:"tags"`
	CreatedAt   string        `json:"createdAt"`
	ModifiedAt  string        `json:"modifiedAt"`
}

type Step struct {
	Index       int     `json:"index"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Image       *string `json:"image"`
}

type Tag struct {
	TagName string    `json:"tagName"`
	TagStem string    `json:"tagStem"`
	Recipes []*Recipe `json:"recipes"`
}
