name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install Protoc
      uses: arduino/setup-protoc@master

    - name: Set up Go 1.x
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Install Go protoc plugin
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && go get google.golang.org/grpc/cmd/protoc-gen-go-grpc && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

    - name: Build
      run: make build -e VERBOSE=true

    - name: Test
      run: make test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Build and publish Docker Image to GitHub Packages Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u publisher --password-stdin docker.pkg.github.com
        make release

  release-dev:
    name: Release Dev
    runs-on: ubuntu-18.04
    needs: build
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Build and publish Docker Image to GitHub Packages Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u publisher --password-stdin docker.pkg.github.com
        make release-dev
