name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install Protoc
      uses: arduino/setup-protoc@master

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Install Go protoc plugin
      run: go install github.com/golang/protobuf/protoc-gen-go

    - name: Build
      run: make build -e VERBOSE=true

    - name: Test
      run: make test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build and publish Docker Image to GitHub Packages Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u publisher --password-stdin docker.pkg.github.com
        make release
